\set ON_ERROR_STOP on

CREATE ROLE chartsdk_migrator LOGIN PASSWORD 'chartsdk-migrator' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE chartsdk_app LOGIN PASSWORD 'chartsdk-app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE chartsdk_source_reader LOGIN PASSWORD 'chartsdk-source-reader' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
